### ISSUE TITLE
opt model ppl bug

### ISSUE THREAD

**Issue by zhsky2017** [spcl/QuaRot#12]
`python main.py --model facebook/opt-125m `

WIKITEXT2 PPL: 27.495

`python main.py --model facebook/opt-125m  --rotate`

WIKITEXT2 PPL: 41950.562

this seem to have a bug?

**Comment by sashkboos** [comment]
Hi @zhsky2017 

Thanks for your issue. 

The current repo is specially developed for LLaMa models and they have some differences (like different MLP, RoPE, etc) with OPT models so such behaviours are expected. We will integrate OPT (and maybe other types of models) soon in our repo :)

**Comment by DavidePaglieri** [comment]
Hi there, are there any updates on OPT integration?

**Comment by sashkboos** [comment]
Hi @DavidePaglieri 

Unfortunately, we haven't worked on this. I would suggest to use [this](https://github.com/microsoft/TransformerCompression/tree/quarot-main) repo. They support more models and also you can extend it quite easily for the new one (like OPT)
