### ISSUE TITLE
Question about reproducing Fig.1

### ISSUE THREAD

**Issue by xinghaow99** [spcl/QuaRot#14]
Hi! Thanks for the great work! 

Been playing with the code today and trying to reproduce Figure 1 in the paper, and here's what I got.
![image](https://github.com/spcl/QuaRot/assets/50691954/f254ed8f-9173-419b-a60a-5abee3d68a9f)

I noticed that the activations after rotation have a larger norm, which does not match the case in Figure 1.

I'm wondering if this is the case or maybe I missed something.

Thanks!

**Comment by xinghaow99** [comment]
Here is my [code](https://gist.github.com/xinghaow99/6c788bd1de18566fca5cec22fc575ece).

**Comment by sashkboos** [comment]
Thanks @xinghaow99 

I think the whole point is about scaling and you can try to scale the distribution using a single number (maybe divide them with the maximum value).

**Comment by xinghaow99** [comment]
Thank you for your response. @sashkboos 

I get the idea now. Just to make sure that incoherent processing does affect the norm of the matrix, right? And did you apply any scaling when plotting Fig.1?

**Comment by sashkboos** [comment]
@xinghaow99 

Yes. We only care about the dynamic range during quantization.
