### ISSUE TITLE
Wrong result obtained in case of w4a16 quantization？

### ISSUE THREAD

**Issue by hyx1999** [spcl/QuaRot#16]
Hi, In my attempt to compare RTN and QuaRot-RTN, I found that QuaRot-RTN showed worse results than RTN and the results were different from the paper. May I ask what could be the cause of this phenomenon?

+ python main.py --model meta-llama/Llama-2-7b-hf --w_rtn --w_asym --bsz 1 --w_bits 4 --a_bits 16 --k_bits 16 --v_bits 16
Arguments: 
{'a_asym': False,
 'a_bits': 16,
 'a_clip_ratio': 1.0,
 'a_groupsize': -1,
 'act_order': False,
 'bsz': 1,
 'cal_dataset': 'wikitext2',
 'capture_layer_io': False,
 'distribute': False,
 'eval_dataset': 'wikitext2',
 'fp32_had': False,
 'hf_token': None,
 'int8_down_proj': False,
 'k_asym': False,
 'k_bits': 16,
 'k_clip_ratio': 1.0,
 'k_groupsize': -1,
 'k_pre_rope': False,
 'layer_idx': 10,
 'lm_eval': False,
 'lm_eval_batch_size': 128,
 'load_qmodel_path': None,
 'model': 'meta-llama/Llama-2-7b-hf',
 'nsamples': 128,
 'percdamp': 0.01,
 'rotate': False,
 'rotate_mode': 'hadamard',
 'rotation_seed': -1,
 'save_name': '20240531_230124',
 'save_path': '/home/huyuxuan/projects/QuaRot-test/fake_quant/experiments/meta-llama/Llama-2-7b-hf/20240531_230124',
 'save_qmodel_path': None,
 'seed': 0,
 'tasks': ['piqa',
           'hellaswag',
           'arc_easy',
           'arc_challenge',
           'winogrande',
           'lambada'],
 'v_asym': False,
 'v_bits': 16,
 'v_clip_ratio': 1.0,
 'v_groupsize': -1,
 'w_asym': True,
 'w_bits': 4,
 'w_clip': False,
 'w_groupsize': -1,
 'w_rtn': True,
 'wandb': False,
 'wandb_id': None,
 'wandb_project': None}
------------------------------------------------------------
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  7.03it/s]
---> Loading meta-llama/Llama-2-7b-hf Model with seq_len: 2048
/home/huyuxuan/miniconda3/lib/python3.9/site-packages/transformers/modeling_utils.py:4481: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
(RtN Quant.) Layers: 100%|██████████████████████████████████████████████████████████████████████████████| 32/32 [00:11<00:00,  2.87it/s]
GPU memory (from rtn_fwrd): 0.08 -> 0.08 GB (0.00 GB)
(Eval) Layers: 100%|████████████████████████████████████████████████████████████████████████████████████| 32/32 [01:30<00:00,  2.82s/it]

WIKITEXT2 PPL: 6.116

+ python main.py --model meta-llama/Llama-2-7b-hf --w_rtn --w_asym --bsz 1 --rotate --w_bits 4 --a_bits 16 --k_bits 16 --v_bits 16
Arguments: 
{'a_asym': False,
 'a_bits': 16,
 'a_clip_ratio': 1.0,
 'a_groupsize': -1,
 'act_order': False,
 'bsz': 1,
 'cal_dataset': 'wikitext2',
 'capture_layer_io': False,
 'distribute': False,
 'eval_dataset': 'wikitext2',
 'fp32_had': False,
 'hf_token': None,
 'int8_down_proj': False,
 'k_asym': False,
 'k_bits': 16,
 'k_clip_ratio': 1.0,
 'k_groupsize': -1,
 'k_pre_rope': False,
 'layer_idx': 10,
 'lm_eval': False,
 'lm_eval_batch_size': 128,
 'load_qmodel_path': None,
 'model': 'meta-llama/Llama-2-7b-hf',
 'nsamples': 128,
 'percdamp': 0.01,
 'rotate': True,
 'rotate_mode': 'hadamard',
 'rotation_seed': -1,
 'save_name': '20240531_231136',
 'save_path': '/home/huyuxuan/projects/QuaRot-test/fake_quant/experiments/meta-llama/Llama-2-7b-hf/20240531_231136',
 'save_qmodel_path': None,
 'seed': 0,
 'tasks': ['piqa',
           'hellaswag',
           'arc_easy',
           'arc_challenge',
           'winogrande',
           'lambada'],
 'v_asym': False,
 'v_bits': 16,
 'v_clip_ratio': 1.0,
 'v_groupsize': -1,
 'w_asym': True,
 'w_bits': 4,
 'w_clip': False,
 'w_groupsize': -1,
 'w_rtn': True,
 'wandb': False,
 'wandb_id': None,
 'wandb_project': None}
------------------------------------------------------------
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 11.65it/s]
---> Loading meta-llama/Llama-2-7b-hf Model with seq_len: 2048
GPU memory (from rotate_model): 2.10 -> 0.14 GB (-1.95 GB)
Rotating: 100%|██████████████████████████████████████████████████████████████████████████████████████| 32/32 [02:39<00:00,  4.98s/layer]
GPU memory (from main): 1.24 -> 0.02 GB (-1.22 GB)
/home/huyuxuan/miniconda3/lib/python3.9/site-packages/transformers/modeling_utils.py:4481: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
(RtN Quant.) Layers: 100%|██████████████████████████████████████████████████████████████████████████████| 32/32 [00:16<00:00,  1.91it/s]
GPU memory (from rtn_fwrd): 0.10 -> 0.10 GB (0.00 GB)
(Eval) Layers: 100%|████████████████████████████████████████████████████████████████████████████████████| 32/32 [01:34<00:00,  2.96s/it]

WIKITEXT2 PPL: 9.114

We used NVIDIA RTX A6000 for our experiments with the following CUDA versions

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+

**Comment by nailimixaM** [comment]
Thanks for your post @hyx1999. You should include `--w_clip` (automatic finding of best weight clipping ratio). Let me know if that fixes the results.

**Comment by hyx1999** [comment]
Thank you very much for your reply, after turning on the --w_clip option I got the same result as the paper.

**Comment by brisker** [comment]
@sashkboos 
@nailimixaM 
But in the Table 5 in the paper, RTN-rotate(6.76 ppl) is better than RTN( 6.99 PPL), right? Is that weird, since the results(rtn-rotate is worse) produced by @hyx1999  is different from Table 5?
![image](https://github.com/user-attachments/assets/0779cc1d-ff90-4322-9659-f1a1b40f1881)
