### ISSUE TITLE
How to deal with GQA?

### ISSUE THREAD

**Issue by mxjmtxrm** [spcl/QuaRot#20]
As title.
I tried to quantize my own model, which has the same structure as llama, except that qkv sets bias=true.
If the attention is GQA (Group Query Attention), a size mismatch error will arise during matmul(Q.T,bias).
how to solve this problem? Looking forward to your reply.

**Comment by RanchiZhao** [comment]
So how to solve? moreover, what above MLA?

**Comment by mxjmtxrm** [comment]
Hi, How to deal with GQA, like Llama3 models?
