### ISSUE TITLE
Question about rotation.

### ISSUE THREAD

**Issue by mxjmtxrm** [spcl/QuaRot#21]
I notice that the rotation of attention and mlp is opposite of what is shown in the fig4&5 of the paper. I am wondering how to keep computational invariance?
embedding : WQ
QKV: WQ
forward: x-> embedding->XQ -> QKV->XQWQ. 
Is there anything I'm missing?

**Comment by ponytaill** [comment]
Hi, I have the same question. Have you figured it out?

**Comment by ponytaill** [comment]
Hi @mxjmtxrm , I have the same question. Have you figured it out?

**Comment by Coco58323** [comment]
In general, Y = X @ W.T
As a result, Y = (X@Q) @ (W@Q).T = X @ W.T

**Comment by ponytaill** [comment]
> In general, Y = X @ W.T As a result, Y = (X@Q) @ (W@Q).T = X @ W.T

@Coco58323 Thanks!
