### ISSUE TITLE
How to get models with only offline rotation (or models for weight-only quantization)

### ISSUE THREAD

**Issue by Tracin** [spcl/QuaRot#24]
Previous chat is here. https://github.com/spcl/QuaRot/issues/22

Let me describe more about this. The only function I call is `rotate_model`, I skip the layernorm fusion and activation quantization. I just save the model once rotation finished, want to make sure two models are 'same'.
For two reasons you mentioned, I think I have dealt with them.
For reason 1, I remove `rotate_ov_proj` call from `rotate_model` [here](https://github.com/spcl/QuaRot/blob/main/fake_quant/rotation_utils.py#L250).
For reason 2, I remove online Hadamard for `down_proj` [here](https://github.com/spcl/QuaRot/blob/main/fake_quant/rotation_utils.py#L173)
Could you guide me anything else for me to do?

Thanks! @sashkboos

**Comment by sashkboos** [comment]
Thanks @Tracin for your issue

You cannot ignore layernorm_fusion as the whole offline rotation relies on the idea of having RMSNorm without weights (check section 3.4 in the paper).

**Comment by Tracin** [comment]
@sashkboos Thanks! I just realize that. XQDiag(a) * Q^TW can not make QQ^T canceled but XQ * Q^TDiag(a)W can. That's cool.
However after merge LN weights to subsequent weights and set it to all ones (or replace it to RMSN), I still can not make this rotated model aligned with original one.
Do you have any idea for this?

**Comment by telemorne** [comment]
@Tracin 
Can you please explain a little more in detail how you altered the script to work with LLama3 for offline weight-only quantization, or if you have a script that would be appreciated?

**Comment by Tracin** [comment]
@telemorne Sure, first remove all online hadamard operations described in this issue.
In `layernorm_fusion`, you need to set LN weights to 1.0 (bias to 0.0 if have any) after fused.
Then `save_pretrained`.

**Comment by telemorne** [comment]
@Tracin Thanks a lot for the reply. After loading the model using this code in a notebook `config = modeling_llama.QuarotLlamaConfig.from_pretrained(
    model_path,
    attn_implementation="flash_attention_2"
)
torch.set_default_dtype(torch.float16)
with transformers.modeling_utils.no_init_weights(): 
    model = modeling_llama.QuarotLlamaForCausalLM(config=config)`

I try to use their evaluator function to get the perplexity. But I get the error: 
![image](https://github.com/spcl/QuaRot/assets/54008081/25cebdeb-7340-42fc-bc02-2a7f362c5eae).
Would you have an idea why this could be happening? I just need a way to save the rotated model in a way where I can quantize the weights easily using different methods Hqq, Awq... and get the perplexity in a straightforward way. Thx in advance

**Comment by telemorne** [comment]
@Tracin Sorry for the numerous questions, one last thing which class did you use to load the model using the from_pretrained function(is it LlamaForCausalLM?) because I am facing some dimensionality issues?

**Comment by Tracin** [comment]
> @Tracin Sorry for the numerous questions, one last thing which class did you use to load the model using the from_pretrained function(is it LlamaForCausalLM?) because I am facing some dimensionality issues?

Yes, please save model using `LlamaForCausalLM` from transformers.
