### ISSUE TITLE
Other quantization results of rotated model

### ISSUE THREAD

**Issue by mxjmtxrm** [spcl/QuaRot#25]
Hi, 
I tried to quantize the rotated model using other quantization methods like awq and omniquant except GPTQ as weight-only quantization. The result is a very dramatic drop. 
The functions I used includes rotation_utils.fuse_layer_norms(model)  and  rotation_utils.rotate_model(model, args). And like #24, I removed rotate_ov_proj and online Hadamard for down_proj.
Which quantization method is the rotation method compatible with? Looking forward to your reply.

**Comment by sashkboos** [comment]
@mxjmtxrm 

Thank you so much for your issue.

We haven't tried other schemes on top of rotated model so far. However, this could be an interesting study. Please share any new results you found with us via email: saleh.ashkboos@inf.ethz.ch

**Comment by Tracin** [comment]
Me too. After verified that rotated model are `computational Invariance` compared to the original one. My rotated model produces very bad result after applied AWQ on it. I am trying to figure it out.

**Comment by sashkboos** [comment]
@Tracin @mxjmtxrm 

I was thinking about this a bit and have some explanation for it. AWQ scales around 1% of the weights before quantization, quantizes the weights, and then applies the inverse of that scaling into the activations. Now, there are two issues:

1. When you apply hadamard matrices, the magnitude of the inputs (activations) and weights will become near each other (check the first figure of our paper). So finding the salient channel based on the activation magnitude may not be optimal anymore.
2. When you fuse the hadamard matrices, scaling (+quantizing) one channel will completely destroy the fusion and your model will not be computational invariance anymore. This may results in higher error.

These are just my thoughts for AWQ and may not be 100% true. But I think this can explain why that scheme performs poorly on rotated model (it is designed based on a very specific nature of LLMs which may not be hold always).

**Comment by mxjmtxrm** [comment]
Make sense.
But the results are also terrible with other quantization methods like HQQ, which conduct quantization without scaling weights and activations.

**Comment by Tracin** [comment]
@sashkboos Thanks for your reply. I want to reproduce the result of weight-only group-wise quantization without AWQ rescaling. This is like Table 5 in your paper (with group quant). Could you provide a command to achieve this?

**Comment by sashkboos** [comment]
@Tracin 

Check [this](https://github.com/spcl/QuaRot/issues/16).

**Comment by sashkboos** [comment]
@Tracin 

I didn't go into the detail of this. For now, I don't have any idea. Please let me know if you have more findings :-)

**Comment by brisker** [comment]
> @sashkboos Thanks for quick response! How could I explain that QuaRotRTN is worse than RTN if no w_clip applied? I think it is 'more fair' when no w_clip applied for both QuaRotRTN and RTN if we do ablation study on Hadamard transformation.

@sashkboos I also encounted such issues. Any idea on this? why RTN-rotate is worse than RTN, if no further tuning like GPTQ is applied?
similar issue [here](https://github.com/spcl/QuaRot/issues/16#issue-2328108411)

**Comment by flymmmfly** [comment]
The same question puzzles me. Can anyone provide help?

**Comment by brisker** [comment]
@sashkboos 

> > [@sashkboos](https://github.com/sashkboos) Thanks for quick response! How could I explain that QuaRotRTN is worse than RTN if no w_clip applied? I think it is 'more fair' when no w_clip applied for both QuaRotRTN and RTN if we do ablation study on Hadamard transformation.
> 
> [@sashkboos](https://github.com/sashkboos) I also encounted such issues. Any idea on this? why RTN-rotate is worse than RTN, if no further tuning like GPTQ is applied? similar issue [here](https://github.com/spcl/QuaRot/issues/16#issue-2328108411)
