### ISSUE TITLE
Question about Hadamard transformation and outlier reduction

### ISSUE THREAD

**Issue by KimythAnly** [spcl/QuaRot#26]
Hi,

I’m very impressed by your work! I have some questions about the Hadamard transformation and outlier reduction.

Consider that we randomly sample a vector from an original space 𝑆 (let's set 𝑆 as 𝑅^8), and apply an exact Hadamard transformation. Suppose this transformation has a _90% probability of reducing the outliers._

We know that the original space 𝑆 and the transformed space 𝑆′ are identical since the Hadamard transformation merely rotates a vector in 𝑅^8 to another vector in 𝑅^8. However, if we apply the transformation to the transformed vector in 𝑆′, the vector will be rotated back to its original form, which would lead to a _90% probability of increasing the outliers in the space 𝑆′_.

How could this be? Am I missing something?

Thanks!

**Comment by sashkboos** [comment]
Thanks @KimythAnly For your issue,

Your intuition is right. Hadamard transformation removes the outliers and as it self inverse (assuming the input is power-of-two for now), applying it to a uniform vector should generate outlier.

This is super interesting to me and we are working on a project build on top of this idea :-)

Please let me know if you have any other question.

**Comment by KimythAnly** [comment]
Thanks for your quick reply! I believe this is a very interesting topic and I'm looking forward to your future research. Keep up the great work!
