### ISSUE TITLE
Relations with SpinQuant?

### ISSUE THREAD

**Issue by RanchiZhao** [spcl/QuaRot#28]
spinquant: https://arxiv.org/abs/2405.16406

**Comment by sashkboos** [comment]
@RanchiZhao 

SpinQuant is a follow-up work that uses the computational invariance idea for quantization. They use a trainable orthogonal transformation and show that this could improve the results (something like 0.1 ppl on large models) in the cost of training the model for a few steps.

**Comment by sashkboos** [comment]
@RanchiZhao 

We haven’t talked to them yet. Microsoft is developing QuaRot here (and maybe other inference engines will do that in the future): https://github.com/microsoft/TransformerCompression
