### ISSUE TITLE
opt model with layernorm,  the input of layernorm can use hadamard transform?

### ISSUE THREAD

**Issue by JiangYongYu1** [spcl/QuaRot#29]
The hadamard transform does not change the norm, but changes the mean. So If the input of layernorm uses hadamard transform, can the equivalence before and after the transformation still be guaranteed?

**Comment by sashkboos** [comment]
Hi @JiangYongYu1 

Thank you so much for your issue. 

I'm not sure I understood your question correctly. But note that you can preserve an orthogonal transformation only with normalization operation (x/norm(x)). However, in the layernorm, we do have mean subtraction, and also learnable parameters. In that case, the equivalence is not guaranteed.

**Comment by JiangYongYu1** [comment]
Thank you for your reply.

Yes, if LayerNorm is used in the transformer block instead of RMSNorm, the Hadamard transform cannot be used before and after normalization while preserving its properties.

**Comment by sashkboos** [comment]
Please check Issue #30 for the same topic

**Comment by JiangYongYu1** [comment]
@sashkboos  Thank you, I misunderstood earlier.
