### ISSUE TITLE
args.distribute_model seems to be undefined

### ISSUE THREAD

**Issue by WeiMa01** [spcl/QuaRot#31]
When I run the fake_quant/main.py with "--lm_eval", It has a error args.distribute_model is not defined.
I am not sure if it is a BUG of the code.

**Comment by sashkboos** [comment]
Thanks @WeiMa01 

can you please let me know what is the error you get? Also, please specify your gpu type and model you are running the code with it (is this baseline model or quantized one?).

I will check

**Comment by WeiMa01** [comment]
> Thanks @WeiMa01
> 
> can you please let me know what is the error you get? Also, please specify your gpu type and model you are running the code with it (is this baseline model or quantized one?).
> 
> I will check

Thank you for replying, actually, I did not find the definition of "args.distribute_model" in the file QuaRot/fake_quant/main.py(line 152), I checked the "parser_gen" function in QuaRot/fake_quant/utils.py(line 71) and did not find the parameter "distribute_model", I found the similar parameter "distribute" in above function, I think is a bug of code, please check if it is right?


I will show the detail of the error later. thank you!

**Comment by sashkboos** [comment]
@WeiMa01 

Fixed (see https://github.com/spcl/QuaRot/commit/13555c70fe3adb00d5c8dcd103f9bc782a5bcb3c).

Thanks
