### ISSUE TITLE
When is online Hadamard applied during evaluation?

### ISSUE THREAD

**Issue by pavelgolikov** [spcl/QuaRot#32]
Hi,
I have installed this QuRot according to instructions (pip install -e .)
I am running the main script from fake_quant as follows: `python main.py --model meta-llama/Llama-2-7b-hf --a_bits 4 --v_bits 4 --k_bits 4 --w_bits 4 --w_clip --rotate`.

I have made a modification to the online hadamard as follows:

```
import quarot
import torch

class OnlineHadamard(torch.nn.Module):
    def __init__(self, hadamard_dim, force_fp32=False):
        super().__init__()
        self.fp32_had = force_fp32
        had_rem_dim, self.rem_dim = quarot.functional.hadamard.get_hadK(hadamard_dim)
        if had_rem_dim is not None:
            self.register_buffer("had_rem_dim", had_rem_dim)
            if not self.fp32_had:
                self.had_rem_dim = self.had_rem_dim.to(torch.float16)
        else:
            self.had_rem_dim = None       
    
    def forward(self, x):
        print(x)
        exit(1)
        x_dtype = x.dtype
        if self.fp32_had:
            x = x.float()
        x = quarot.functional.matmul_hadU_cuda(x, self.had_rem_dim, self.rem_dim)
        x = x.to(x_dtype)
        return x
```

As you can see, I have added a print and an early exit in the forward pass.
What I get as a result is the script runs to completion without exiting, indicating that the above script never runs the OnlineHadamard. I thought the script is supposed to evaluate QuaRot with OnlineHadamard. Am I missing something?

Best Regards,

Pavel.

**Comment by stamina1121** [comment]
you lack the parameter: "--rotate", which can launch rotate function.
