### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by zhentingqi** [spcl/QuaRot#37]
Hi! Any guide on using the modules provided in the repo to do inference in a plug-and-play manner? In my case CMake compiling is not available so running the repo is not achievable. Thanks!

**Comment by johndpope** [comment]
your work is blowing up on twitter -https://x.com/AtakanTekparmak/status/1823776892421365786

**Comment by sashkboos** [comment]
@zhentingqi 

Thank you so much for your issue. 

For now, we only support through CMaKe and our setup files are using that. However, we are working with other teams to integrate QuaRot into other repo for LLM inference. We will announce it later.

Thanks
