### ISSUE TITLE
[Inference speed] Speed up on prefilling stage, slow down on decoding stage

### ISSUE THREAD

**Issue by ChenMnZ** [spcl/QuaRot#38]
Thanks for your outstanding works.

I find that the cost of on-line hadamard transformation  is negligible in the prefilling stage (matrix-matrix manipulation), while significantly slow down the speed in the decoding stage (vector-matrix manipulation).

Are there any potential solutions to this problem?

**Comment by Coco58323** [comment]
I also have questions about the inference performance.

How can I reproduce the result from Figure 6 in paper? I have rerun e2e/benchmark_layers.py and e2e/benchmark.py and benchmarks/*. Few of the tests show that INT4 inference is faster than FP16, even slower in most cases, not saying 3.2x speedup as demonstrated in section 5.2. I am not questioning the correctness. I would grateful for pointing out my mistakes. The test is on one A100 GPU with LLaMA2-7b, and Python 3.9. The rest config follows the repo's requirements.

**Comment by sashkboos** [comment]
Thanks @Coco58323 

All experiments we have done were on RTX GPUs and the results were report on that (check Section 5). We only used A100 for doing weight quantization (actually, applying GPTQ) and the rest of the experiments were done on 3090.
