### ISSUE TITLE
Question about online hadamard  transformation before down-proj and o_proj

### ISSUE THREAD

**Issue by ChenMnZ** [spcl/QuaRot#4]
Hi,

As mentioned in the paper, QuaRot insert on-line Hadamard operations to improve the activation quantization.

So, in my understanding, the on-line Hadamard operations can be remove for weight-only quantization.

However, I find that the model would collapse after removing the following codes (related to on-line Hadamard operations):
https://github.com/spcl/QuaRot/blob/07e4f2ea6ad19627b9a0808ed1f820433fb8e9f4/fake_quant/main.py#L30-L45

For example, I test the full-precision model with rotation with following command:
```
python main.py --model meta-llama//Llama-2-7b-hf --rotate  --a_bits 16 --v_bits 16 --k_bits 16 --w_bits 16
```
The output is normal for the current repo (5.47 ppl for WikiText). Nevertheless, the ppl increase to 3e4 after I deleting the aforementioned on-line Hadamard operations.

**Comment by flymmmfly** [comment]
Can you tell me how you did it? I encountered the same problem.
