### ISSUE TITLE
apply_exact_had_to_linear for v_proj.bias if v_proj.bias is not None

### ISSUE THREAD

**Issue by dyou-dev** [spcl/QuaRot#40]
When I tested a phi model with a bias in v_proj, I found the following code was needed.
```
def rotate_ov_proj(layer, model_type, head_num, head_dim):
    ...
    apply_exact_had_to_linear(v_proj, had_dim=head_dim, output=True)
    # added
    if v_proj.bias is not None:
        apply_exact_had_to_linear_bias(v_proj, had_dim=head_dim, output=True)
    # added end
    apply_exact_had_to_linear(o_proj, had_dim=-1, output=False)
    ...
```

I added apply_exact_had_to_linear_bias()  which was similar to apply_exact_had_to_linear().

**Comment by sashkboos** [comment]
Thanks @dyou-dev for your issue. 

Yes this is true. Our code (in this repo) is developed for LLaMa model and needs some changes (like having biases in your code) to be compatible with other models. However, [this](https://github.com/microsoft/TransformerCompression/tree/quarot-main/src/quarot) repo implemented these things and extended QuaRot for other models (including phi-3).

**Comment by quanwei0** [comment]
@sashkboos @dyou-dev I am struggling to apply QuaRot to a model with a bias in v_proj. Could you please share your code apply_exact_had_to_linear_bias()? Thank you!

**Comment by sashkboos** [comment]
@quanwei0 

you can check this function for example: 
https://github.com/microsoft/TransformerCompression/blob/main/src/slicegpt/rotate.py#L47
