### ISSUE TITLE
[Q] Having not matched size Hadamard matrix 

### ISSUE THREAD

**Issue by Coco58323** [spcl/QuaRot#41]
Thanks for the great work! I have well reproduced the result on small models, however, facing problems with large models, e.g. Qwen2-72B, Qwen2-14B.
The problem comes from the intermediate size sometimes goes weird, e.g. 29568 = 2^n * 231, where I cannot construct a Hadamard matrix in order of 231 according to [http://www.neilsloane.com/hadamard/index.html](url).
For static rotation, we could fix this problem by picking up a random/optimized orthogonal matrix instead. However for online computation, a non-Hadamard matrix would degrade the inference speed.
Am I missing something, please help fix the problem.

**Comment by JingyangXiang** [comment]
https://github.com/sagemath/sage/tree/e042294b5ed8e1cb564965079e20e4270ccde340 ，this repo can help us to generate hadamard matrix, I adopt it for Qwen2-7B

**Comment by Coco58323** [comment]
> https://github.com/sagemath/sage/tree/e042294b5ed8e1cb564965079e20e4270ccde340 ，this repo can help us to generate hadamard matrix, I adopt it for Qwen2-7B

Thanks for info! It seems we could easily get hadmard matrices in order of 231*4 with 'sage', and we would quickly test with it. (Though Qwen2-7B could get its hadamard matrix according to [http://www.neilsloane.com/hadamard/index.html](url))

**Comment by sashkboos** [comment]
Thanks @Coco58323 for your issue.

Yes, you are right. There are two different issues here:

1. Having a Hadamard matrix of size 231. This is not included in the [http://www.neilsloane.com/hadamard/index.html](https://github.com/spcl/QuaRot/issues/url). You can use something like Sage (as @JingyangXiang suggested) to get such matrix. 

2. The more challenging issue is with the performance (as you mentioned). One way of solving this, you need to extend dao's [kernel](https://github.com/Dao-AILab/fast-hadamard-transform) to support your specific matrix size. I agree that this is not a simple task to do and we are working on it (for the next versions of QuaRot)/

Thanks

**Comment by Coco58323** [comment]
Thanks for the quick reply, my problem has been solved temporarily.
From an engineering perspective, would it be advantageous to directly remove the 'online' rotation component and employ the A8W8 kernel instead?

**Comment by sashkboos** [comment]
@Coco58323 

I don't think 8-bit kernel solves the issue as you will have large outliers which may result in accuracy degradation (even with 8-bit kernels). However, we haven't tried this from our side and you may get reasonable accuracy.

If you are in the generation phase, then I suggest to keep the inputs in FP16 (without quantization) and quantize the weights of that layer using GPTQ and use FP16xINT4 kernels (like [Marlin](https://github.com/IST-DASLab/marlin)). 

I will close this issue. Please let me know if you have any other question :-)
