### ISSUE TITLE
How is perplexity calculated with the KV cache?

### ISSUE THREAD

**Issue by tsengalb99** [spcl/QuaRot#42]
I've noticed QuaRot and other KV cache papers include perplexity, but it is unclear to me how a quantized KV cache is used during perplexity calculation. Do you have a detailed writeup of how you calculate ppl with the quantized kv cache? Thanks

**Comment by sashkboos** [comment]
Thanks @tsengalb99 for your issue.

We just simulate the PPL with quantized cache in our experiments. You can find the main function for that [here](https://github.com/spcl/QuaRot/blob/main/fake_quant/eval_utils.py#L11).
