### ISSUE TITLE
question about Hadamard dimension

### ISSUE THREAD

**Issue by mxjmtxrm** [spcl/QuaRot#44]
When I tried to quantize my own model using quarot, I met a ValueError:
```
ValueError: Unsupported Hadamard dimension: 13696
```
How to solve this problem?

**Comment by sashkboos** [comment]
Thanks @mxjmtxrm for your issue. 

You can check the list of Hadamard matrices [here](http://www.neilsloane.com/hadamard/index.html). I checked and I haven't found that dimension (or it's multiplication of power-two) in the matrices there (for example, you need to find a matrix of size `214` so it will be `13696 = 214*64`).

**Comment by mxjmtxrm** [comment]
Is there another way to apply on-the-fly Hadamard transform for down_proj? As there is no Hadamard matrice suitable for the dimension.

**Comment by sashkboos** [comment]
You can apply a Hadamard transformation on a single identity matrix and get that matrix. Then you can apply it using normal matrix-matrix multiplication

**Comment by mxjmtxrm** [comment]
Could you please give me a code example?

**Comment by sashkboos** [comment]
Check this:

https://github.com/spcl/QuaRot/blob/main/fake_quant/hadamard_utils.py#L58
