### ISSUE TITLE
Reproducing Table 7 (weight-only quantization results)

### ISSUE THREAD

**Issue by SShock92** [spcl/QuaRot#52]
Thank you for sharing the code of the awesome work!

I have difficulty reproducing weight-only quantization results in Table 7, especially W2A16 results.
How did you set the quantization grid?
I have 1) tried the standard Min-Max grid and 2) activated 'MSE' option in the weight quantizer, but the perplexity of quantized models is much larger than 100.

**Comment by sashkboos** [comment]
@SShock92 

Thanks for your issue. Can you please put the complete list of arguments you are using (for example, the command that you run the code with) here?

**Comment by sashkboos** [comment]
Please check [this](https://github.com/spcl/QuaRot/issues/3).
