### ISSUE TITLE
Problem when reproducing w4a4kv4 quantization

### ISSUE THREAD

**Issue by ZijianYY** [spcl/QuaRot#55]
Dear authors,

Very nice work and I have learned a lot from your work.

But I got one problem: when I try to reproduce the w4a4kv4 quantization on llama-2-7b, I use the command 
`python main.py --model meta-llama/Llama-2-7b-hf  --rotate --a_bits 4 --v_bits 4 --k_bits 4 --w_bits 4 --w_clip`
in Table 1, the result should be **6.10**. But I have tried several times and the result is around **6.35**.
I know it is nor far from the result in the paper but I just want to know if I'm missing something or it is just caused by the random seed.

**Comment by ZijianYY** [comment]
The result means wikitext2 perplexity.

**Comment by sashkboos** [comment]
Thanks @ZijianYY for your issue. The additional ppl could be get by adding clipping ratios. Please use `--a_clip_ratio`, `--k_clip_ratio`, and `--v_clip_ratio` with proper numbers (you can find them in the paper) to get additional improvements

**Comment by sashkboos** [comment]
The list of all arguments could be found [here](https://github.com/spcl/QuaRot/tree/main/fake_quant#fake-quantization-in-quarot)

**Comment by ZijianYY** [comment]
Thanks! Perfectly solved my problem.
