### ISSUE TITLE
[question] Is it possible to quantize Mixtral?

### ISSUE THREAD

**Issue by accupham** [spcl/QuaRot#6]
The new 8x22b mixtral would be a great model to quantize in 4bit. Can this method be applied to MoEs?

**Comment by sashkboos** [comment]
Thanks @accupham for your question. 

We are working on those kind of models to integrate our scheme into them. There is more to come. Stay tuned :)

**Comment by Niko-zyf** [comment]
Is there any progress in MOE support?

**Comment by sashkboos** [comment]
@Niko-zyf 

Yes. We have integrated Mixtral in [this](https://github.com/microsoft/TransformerCompression/tree/quarot-main/src) repo. You can find the adapter [here](https://github.com/microsoft/TransformerCompression/blob/quarot-main/src/quarot/adapters/mixtral_adapter.py).
