### ISSUE TITLE
Question about whether it is necessary to fuse layernorm to linear

### ISSUE THREAD

**Issue by Oliver-ss** [spcl/QuaRot#8]
For llama model, it seems unnecessary and why https://github.com/spcl/QuaRot/blob/main/fake_quant/main.py#L26 fuses before rotation?

Thx!

**Comment by Oliver-ss** [comment]
Hi @sashkboos ,

Thank you for your explanation and excellent work.

Based on this rotation-invariant method, I tried some other llm models and found that on certain bfloat16 models, rotating the model weights can lead to the final results collapsing maybe due to accumulated numerical errors. Have you observed similar phenomena and do you have any suggestions (I have used float64 data type for rotation matmul)?

**Comment by sashkboos** [comment]
@Oliver-ss 

Thanks. 

We have tried LLaMa and a few OPT models so far and we didn't see any changes in the PPL so far. However, those models are in FP16 and I think Falcon uses BF16. Which model have you tried and what were the PPL changes? It would be great if you provide some code to reproduce the issue so I can take a look at it.

**Comment by Oliver-ss** [comment]
@sashkboos 

Thanks. 

I will try to make a smallest reproducible work later.

**Comment by brisker** [comment]
> Hi @sashkboos ,
> 
> Thank you for your explanation and excellent work.
> 
> Based on this rotation-invariant method, I tried some other llm models and found that on certain bfloat16 models, rotating the model weights can lead to the final results collapsing maybe due to accumulated numerical errors. Have you observed similar phenomena and do you have any suggestions (I have used float64 data type for rotation matmul)?


Have you solved the bf16 numerical issue when rotating?
@Oliver-ss

**Comment by wenhuach21** [comment]
> Hi @Oliver-ss
> 
> Thanks for your question.
> 
> Actually, there is a difference between LLaMa [RMSNorm](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L76-L90) and [ours](https://github.com/spcl/QuaRot/blob/main/fake_quant/model_utils.py#L163-L182) (where we fuse the weights into the next layer). So we need to fuse those normalization layers.
> 
> Thanks.

Hi, I'm also curious why you chose to fuse the layer norm. Based on this explanation, why didn't you use the same implementation?

**Comment by sashkboos** [comment]
@wenhuach21 

The main difference is the weight parameters. We do not have any weights in our Normalization module as we assumed they are already fused into adjacent linear layers

**Comment by wenhuach21** [comment]
> @wenhuach21
> 
> The main difference is the weight parameters. We do not have any weights in our Normalization module as we assumed they are already fused into adjacent linear layers

Thanks for your quick reply. What I mean is why not just using the same implementation of norm layer with weight parameters and remove the fuse function, is it more easier?

**Comment by sashkboos** [comment]
I think that should be possible as well (although you need to have more parameters in your module).

**Comment by wenhuach21** [comment]
> I think that should be possible as well (although you need to have more parameters in your module).

I see, thanks. The reason I asked is that I initially thought the fused layernorm might smooth the activation, similar to SmoothQuant, since only the 'norm' operation remains without scaling. I wondered if this was intentional.While I found this approach useful in LLaMA, it had a negative impact on Phi3, Qwen2, and Mistral v0.2 in my test scenarios

**Comment by brisker** [comment]
It seems that not only norm fusing can be harmful, the rotation can also be harmful, even for float model accuracy.

**Comment by wenhuach21** [comment]
> I think that should be possible as well (although you need to have more parameters in your module).

After debugging the code, I think that this is not true. WQ * S * Q^T * X does not equal WX, where S represents the layernorm scale, that's the reason why layernorm must be fused.

**Comment by sashkboos** [comment]
@wenhuach21 

I think you misunderstood my point. You should always fuse the scales into the weights before rotation. My point was that you can use HF implementation and there isn't any differences between ours and their implementation except for removing the weights after fusion (see above).

**Comment by wenhuach21** [comment]
> @wenhuach21
> 
> I think you misunderstood my point. You should always fuse the scales into the weights before rotation. My point was that you can use HF implementation and there isn't any differences between ours and their implementation except for removing the weights after fusion (see above).

I see. Thanks.
